server.port=8888

spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/charan8643/Config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

logging.level.root=INFO
logging.level.org.springframework.cloud=DEBUG

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html